function createNode() {
    var container = document.createDocumentFragment();
    var e_0 = document.createElement("div");
    var e_1 = document.createElement("link");
    e_1.setAttribute("rel", "stylesheet");
    e_1.setAttribute("href", "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css");
    e_0.appendChild(e_1);
    var e_2 = document.createElement("style");
    e_2.appendChild(document.createTextNode("\n* {\nmargin: 0;\npadding: 0;\nbox-sizing: border-box;\n}\n.ad-modal {\ndisplay: flex;\nposition: fixed;\ntop: 0;\nleft: 0;\nwidth: 100%;\nheight: 100%;\nbackground-color: rgba(0, 0, 0, 0.9);\nz-index: 10000;\nalign-items: center;\njustify-content: center;\npadding: 15px;\nanimation: fadeIn 0.5s ease;\n}\n@keyframes fadeIn {\nfrom { opacity: 0; }\nto { opacity: 1; }\n}\n.modal-content {\nbackground: linear-gradient(135deg, #ffffff, #f9f9f9);\nborder-radius: 20px;\nwidth: 100%;\nmax-width: 420px;\nbox-shadow: 0 25px 60px rgba(0, 0, 0, 0.5);\noverflow: hidden;\nposition: relative;\nanimation: modalAppear 0.6s cubic-bezier(0.175, 0.885, 0.32, 1.275);\nborder: 3px solid #e74c3c;\n}\n@keyframes modalAppear {\nfrom { opacity: 0; transform: scale(0.85) translateY(40px); }\nto { opacity: 1; transform: scale(1) translateY(0); }\n}\n.modal-header {\nbackground: linear-gradient(to right, #e74c3c, #c0392b);\ncolor: white;\npadding: 20px 15px;\ntext-align: center;\nposition: relative;\n}\n.modal-header h2 {\nfont-size: 1.6rem;\nmargin-bottom: 8px;\ndisplay: flex;\nalign-items: center;\njustify-content: center;\ngap: 8px;\npadding: 0 10px;\n}\n.modal-header p {\nfont-size: 1.1rem;\ndisplay: flex;\nalign-items: center;\njustify-content: center;\ngap: 8px;\npadding: 0 10px;\n}\n.modal-body {\npadding: 20px 15px;\ntext-align: center;\n}\n.modal-body p {\nfont-size: 1rem;\nline-height: 1.6;\ncolor: #555;\nmargin-bottom: 12px;\ntext-align: left;\npadding-left: 5px;\ndisplay: flex;\nalign-items: flex-start;\ngap: 8px;\n}\n.ad-image {\nwidth: 100%;\nmargin: 15px 0;\nborder-radius: 12px;\noverflow: hidden;\nbox-shadow: 0 5px 15px rgba(0,0,0,0.1);\n}\n.ad-image img {\nwidth: 100%;\nheight: auto;\ndisplay: block;\nobject-fit: cover;\n}\n.links-container {\nbackground: #f8f9fa;\nborder-radius: 12px;\npadding: 15px;\nmargin: 15px 0;\ntext-align: left;\n}\n.link-item {\nmargin-bottom: 12px;\npadding: 12px;\nbackground: white;\nborder-radius: 8px;\ndisplay: flex;\nalign-items: center;\ntransition: all 0.3s ease;\nborder-left: 4px solid #3498db;\n}\n.link-item:hover {\ntransform: translateX(5px);\nbox-shadow: 0 4px 12px rgba(0,0,0,0.1);\nborder-left: 4px solid #e74c3c;\n}\n.link-icon {\nfont-size: 1.3rem;\ncolor: #e74c3c;\nmargin-right: 12px;\nmin-width: 25px;\ntext-align: center;\n}\n.link-text {\nflex: 1;\noverflow: hidden;\n}\n.link-text a {\ncolor: #3498db;\ntext-decoration: none;\nfont-weight: bold;\nfont-size: 0.95rem;\nword-break: break-all;\ndisplay: block;\n}\n.link-text a:hover {\ntext-decoration: underline;\ncolor: #e74c3c;\n}\n.tags {\ndisplay: flex;\nflex-wrap: wrap;\ngap: 8px;\njustify-content: center;\nmargin-top: 15px;\n}\n.tag {\nbackground: #e74c3c;\ncolor: white;\npadding: 4px 12px;\nborder-radius: 20px;\nfont-size: 0.85rem;\n}\n.close-button {\nposition: absolute;\ntop: 12px;\nright: 15px;\nfont-size: 1.8rem;\ncolor: white;\ncursor: pointer;\ntransition: transform 0.3s ease;\nbackground: rgba(0,0,0,0.2);\nwidth: 36px;\nheight: 36px;\nborder-radius: 50%;\ndisplay: flex;\nalign-items: center;\njustify-content: center;\nline-height: 1;\n}\n.close-button:hover {\ntransform: rotate(90deg) scale(1.1);\nbackground: rgba(0,0,0,0.4);\n}\n.countdown-bar {\nheight: 6px;\nbackground: #ecf0f1;\nborder-radius: 3px;\nmargin-top: 20px;\noverflow: hidden;\n}\n.countdown-progress {\nheight: 100%;\nwidth: 100%;\nbackground: linear-gradient(to right, #2ecc71, #3498db);\nborder-radius: 3px;\nanimation: countdown 10s linear forwards;\n}\n@keyframes countdown {\nfrom { width: 100%; }\nto { width: 0%; }\n}\n.countdown-text {\nfont-size: 0.9rem;\ncolor: #7f8c8d;\nmargin-top: 10px;\ntext-align: center;\n}\n.ad-badge {\nposition: absolute;\ntop: 50px;\nright: -10px;\nbackground: #e74c3c;\ncolor: white;\nfont-weight: bold;\npadding: 4px 12px;\nborder-radius: 20px;\nfont-size: 0.8rem;\ntransform: rotate(5deg);\nbox-shadow: 0 4px 12px rgba(0,0,0,0.2);\nz-index: 10;\n}\n.mobile-indicator {\ndisplay: none;\ntext-align: center;\nbackground: rgba(255, 255, 255, 0.2);\npadding: 10px;\nborder-radius: 10px;\nmargin-top: 15px;\ncolor: white;\n}\n/* 移动端优化 */\n@media (max-width: 768px) {\n.modal-header h2 {\nfont-size: 1.4rem;\n}\n.modal-header p {\nfont-size: 1rem;\n}\n.modal-body p {\nfont-size: 0.95rem;\n}\n.link-item {\npadding: 10px;\n}\n.link-text a {\nfont-size: 0.9rem;\n}\n.mobile-indicator {\ndisplay: block;\n}\n}\n@media (max-width: 480px) {\n.modal-content {\nborder-radius: 18px;\n}\n.modal-header {\npadding: 18px 12px;\n}\n.modal-header h2 {\nfont-size: 1.3rem;\n}\n.modal-header p {\nfont-size: 0.95rem;\n}\n.modal-body {\npadding: 15px 12px;\n}\n.modal-body p {\nfont-size: 0.9rem;\nmargin-bottom: 10px;\n}\n.links-container {\npadding: 12px;\n}\n.link-icon {\nfont-size: 1.1rem;\nmargin-right: 10px;\n}\n.close-button {\ntop: 10px;\nright: 12px;\nfont-size: 1.6rem;\nwidth: 32px;\nheight: 32px;\n}\n}\n"));
    e_0.appendChild(e_2);
    e_0.appendChild(document.createComment(" 流量卡广告弹窗 "));
    var e_3 = document.createElement("div");
    e_3.setAttribute("id", "advertised-modal");
    e_3.setAttribute("class", "ad-modal");
    var e_4 = document.createElement("div");
    e_4.setAttribute("class", "modal-content");
    var e_5 = document.createElement("div");
    e_5.setAttribute("class", "ad-badge");
    e_5.appendChild(document.createTextNode("限时优惠"));
    e_4.appendChild(e_5);
    var e_6 = document.createElement("div");
    e_6.setAttribute("class", "modal-header");
    var e_7 = document.createElement("h2");
    var e_8 = document.createElement("i");
    e_8.setAttribute("class", "fas fa-sim-card");
    e_7.appendChild(e_8);
    e_7.appendChild(document.createTextNode(" ☎️ 大额流量卡免费申领"));
    e_6.appendChild(e_7);
    var e_9 = document.createElement("p");
    var e_10 = document.createElement("i");
    e_10.setAttribute("class", "fas fa-car");
    e_9.appendChild(e_10);
    e_9.appendChild(document.createTextNode(" 🚘 陌轩通讯 每日上新 🆕"));
    e_6.appendChild(e_9);
    var e_11 = document.createElement("span");
    e_11.setAttribute("class", "close-button");
    e_11.appendChild(document.createTextNode("×"));
    e_6.appendChild(e_11);
    e_4.appendChild(e_6);
    var e_12 = document.createElement("div");
    e_12.setAttribute("class", "modal-body");
    e_12.appendChild(document.createComment(" 新增广告图片 "));
    var e_13 = document.createElement("div");
    e_13.setAttribute("class", "ad-image");
    var e_14 = document.createElement("img");
    e_14.setAttribute("src", "https://s2.loli.net/2025/06/04/XsehWozJNU6kZVA.jpg");
    e_14.setAttribute("alt", "流量卡广告");
    e_13.appendChild(e_14);
    e_12.appendChild(e_13);
    var e_15 = document.createElement("div");
    e_15.setAttribute("class", "links-container");
    var e_16 = document.createElement("div");
    e_16.setAttribute("class", "link-item");
    var e_17 = document.createElement("div");
    e_17.setAttribute("class", "link-icon");
    e_17.appendChild(document.createTextNode("➜"));
    e_16.appendChild(e_17);
    var e_18 = document.createElement("div");
    e_18.setAttribute("class", "link-text");
    var e_19 = document.createElement("a");
    e_19.setAttribute("href", "https://sourl.cn/yrm8S6");
    e_19.setAttribute("target", "_blank");
    e_19.appendChild(document.createTextNode("https://sourl.cn/yrm8S6"));
    e_18.appendChild(e_19);
    e_16.appendChild(e_18);
    e_15.appendChild(e_16);
    var e_20 = document.createElement("div");
    e_20.setAttribute("class", "link-item");
    var e_21 = document.createElement("div");
    e_21.setAttribute("class", "link-icon");
    e_21.appendChild(document.createTextNode("➜"));
    e_20.appendChild(e_21);
    var e_22 = document.createElement("div");
    e_22.setAttribute("class", "link-text");
    var e_23 = document.createElement("a");
    e_23.setAttribute("href", "https://sourl.cn/ADdLJZ");
    e_23.setAttribute("target", "_blank");
    e_23.appendChild(document.createTextNode("https://sourl.cn/ADdLJZ"));
    e_22.appendChild(e_23);
    e_20.appendChild(e_22);
    e_15.appendChild(e_20);
    e_12.appendChild(e_15);
    var e_24 = document.createElement("p");
    var e_25 = document.createElement("i");
    e_25.setAttribute("class", "fas fa-tag");
    e_25.setAttribute("style", "color: #27ae60;");
    e_24.appendChild(e_25);
    e_24.appendChild(document.createTextNode(" 💰免费申领，邮费全免，非物联卡"));
    e_12.appendChild(e_24);
    var e_26 = document.createElement("p");
    var e_27 = document.createElement("i");
    e_27.setAttribute("class", "fas fa-check-circle");
    e_27.setAttribute("style", "color: #e74c3c;");
    e_26.appendChild(e_27);
    e_26.appendChild(document.createTextNode(" 🔴缺流量卡可以冲，支持异地注销！"));
    e_12.appendChild(e_26);
    var e_28 = document.createElement("p");
    var e_29 = document.createElement("i");
    e_29.setAttribute("class", "fas fa-exclamation-triangle");
    e_29.setAttribute("style", "color: #9b59b6;");
    e_28.appendChild(e_29);
    e_28.appendChild(document.createTextNode(" 🟣✋慢🈚️，若下架可购同类卡片"));
    e_12.appendChild(e_28);
    var e_30 = document.createElement("p");
    var e_31 = document.createElement("i");
    e_31.setAttribute("class", "fas fa-id-card");
    e_31.setAttribute("style", "color: #e74c3c;");
    e_30.appendChild(e_31);
    e_30.appendChild(document.createTextNode(" 🔴全部官方卡，需真实信息办理"));
    e_12.appendChild(e_30);
    var e_32 = document.createElement("div");
    e_32.setAttribute("class", "tags");
    var e_33 = document.createElement("div");
    e_33.setAttribute("class", "tag");
    e_33.appendChild(document.createTextNode("#好卡推荐"));
    e_32.appendChild(e_33);
    var e_34 = document.createElement("div");
    e_34.setAttribute("class", "tag");
    e_34.appendChild(document.createTextNode("#电话卡"));
    e_32.appendChild(e_34);
    var e_35 = document.createElement("div");
    e_35.setAttribute("class", "tag");
    e_35.appendChild(document.createTextNode("#流量卡"));
    e_32.appendChild(e_35);
    e_12.appendChild(e_32);
    var e_36 = document.createElement("div");
    e_36.setAttribute("class", "countdown-bar");
    var e_37 = document.createElement("div");
    e_37.setAttribute("class", "countdown-progress");
    e_36.appendChild(e_37);
    e_12.appendChild(e_36);
    var e_38 = document.createElement("div");
    e_38.setAttribute("class", "countdown-text");
    e_38.appendChild(document.createTextNode("10秒钟后自动关闭"));
    e_12.appendChild(e_38);
    e_4.appendChild(e_12);
    e_3.appendChild(e_4);
    e_0.appendChild(e_3);
    var e_39 = document.createElement("script");
    e_39.appendChild(document.createTextNode("\ndocument.addEventListener('DOMContentLoaded', function() {\n// 获取元素\nvar adModal = document.getElementById(\"advertised-modal\");\nvar closeButton = document.querySelector(\".close-button\");\nvar countdownProgress = document.querySelector(\".countdown-progress\");\nvar countdownText = document.querySelector(\".countdown-text\");\nvar countdownTimer;\nvar timeLeft = 10; // 倒计时时间（秒）\n// 显示广告弹窗\nfunction showAd() {\nadModal.style.display = \"flex\";\nstartAutoClose();\n}\n// 开始10秒自动关闭\nfunction startAutoClose() {\n// 重置倒计时时间\ntimeLeft = 10;\nupdateCountdownText();\n// 重置进度条动画\ncountdownProgress.style.animation = 'none';\nsetTimeout(() => {\ncountdownProgress.style.animation = 'countdown 10s linear forwards';\n}, 10);\n// 清除之前的计时器\nif (countdownTimer) clearInterval(countdownTimer);\n// 每秒更新倒计时文本\ncountdownTimer = setInterval(function() {\ntimeLeft--;\nupdateCountdownText();\nif (timeLeft <= 0) {\ncloseAd();\n}\n}, 1000);\n}\n// 更新倒计时文本\nfunction updateCountdownText() {\ncountdownText.textContent = `${timeLeft}秒钟后自动关闭`;\n}\n// 关闭广告弹窗\nfunction closeAd() {\nadModal.style.display = \"none\";\n// 清除计时器\nif (countdownTimer) clearInterval(countdownTimer);\n}\n// 点击关闭按钮时关闭弹窗\ncloseButton.addEventListener('click', closeAd);\n// 点击弹窗外的区域时关闭弹窗\nadModal.addEventListener('click', function(event) {\nif (event.target === adModal) {\ncloseAd();\n}\n});\n// 页面加载时显示广告（每次刷新都显示）\nsetTimeout(showAd, 1500);\n});\n"));
    e_0.appendChild(e_39);
    container.appendChild(e_0);
    return container;
}